#接下來會應用底下的讀寫分離提高SQL效能,SOURCES為寫,REPLICAS為讀
#export SOURCES_HOST=127.0.0.1
#export SOURCES_PORT=5435
#export SOURCES_USER=postgres
#export SOURCES_PASSWORD=pg654321
#export SOURCES_DATABASE=siir
#export SOURCES_SSLMODE=disable

#export REPLICAS_HOST=127.0.0.1
#export REPLICAS_PORT=5435
#export REPLICAS_USER=siir
#export REPLICAS_PASSWORD=pg654321
#export REPLICAS_DATABASE=siir
#export REPLICAS_SSLMODE=disable
#air

export DB_REPLICAS=0
export SOURCES_HOST=127.0.0.1
export SOURCES_PORT=5432
export SOURCES_USER=
export SOURCES_PASSWORD=
export SOURCES_DATABASE=
export SOURCES_SSLMODE=disable
air

export PUBLIC = ""
export PRIVATE = ""